# Generated by Django 2.2.4 on 2019-09-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_verify', '0002_device_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='status',
            new_name='online',
        ),
    ]
